name: Elixir CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ${{ matrix.os }} 
    name: OTP ${{matrix.otp}} / Elixir ${{matrix.elixir}}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
        # otp: ['22.2', '23.3.4.11', '24.2.2']
        otp: ['22.2', '24.2.2']
        elixir: ['1.9.0', '1.9.4', '1.10.4', '1.11.4', '1.12.3', '1.13.3']
        # OTP and Elixir Compatibility
        # https://hexdocs.pm/elixir/1.13/compatibility-and-deprecations.html#compatibility-between-elixir-and-erlang-otp
        exclude:
          - otp: 24.2.2
            elixir: [1.9.0, 1.9.4, 1.10.4]
          # - otp: 24.2.2
          #   elixir: 1.9.4
          # - otp: 24.2.2
          #   elixir: 1.10.4
    steps:
    - uses: actions/checkout@v2
    - name: Setup elixir
      uses: erlef/setup-beam@v1
      with:
        otp-version: ${{matrix.otp}}
        elixir-version: ${{matrix.elixir}}
    - name: Install Dependencies
      run: mix deps.get
    - name: Run Tests
      run: mix test
